version: '3'

services:
  api:
    restart: always
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      - VIRTUAL_HOST=api.stocksir.app
      - LETSENCRYPT_HOST=api.stocksir.app
  database:
    restart: always
    env_file: .env
    container_name: database
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}