version: '3'

services:
  database:
    restart: always
    container_name: database
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
   api:
    restart: always
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      - VIRTUAL_HOST=api.stocksir.app
      - LETSENCRYPT_HOST=api.stocksir.app
volumes:
  pgdata: {}
