# Arquivo compose para executar toda a infraestrutura necessária para o back-end do Stocks. Esse compose não é usado no ambiente de produção; os contâiners
# são inicializados manualmente por linha de comando.

version: '3'

services:
  database:
    container_name: database
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stocks
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  pgdata: {}