version: '3'

services:
  stocks-server:
    container_name: stocks-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      ConnectionStrings__DefaultConnection: "Host=database;Database=postgres;Username=postgres;Password=postgres"
  database:
    container_name: database
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}